steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/possible-haven-397802/kube/bug:$SHORT_SHA'
  - '.'



- name: snyk/snyk-cli:npm
  args:
    - '-c'
    - |-
      snyk config set api=${_SNYK_TOKEN}
      snyk test --severity-threshold=medium || true 
  id: Snyk Open Source Test 
  entrypoint: bash

- name: snyk/snyk-cli:npm
  args:
    - '-c'
    - |-
      snyk config set api=${_SNYK_TOKEN}
      snyk code test --severity-threshold=medium || true
  id: Snyk Code Test
  entrypoint: bash 

- name: snyk/snyk-cli:npm
  args:
    - '-c'
    - |-
      snyk config set api=${_SNYK_TOKEN}
      snyk monitor --severity-threshold=medium || true
  id: Snyk Monitor
  entrypoint: bash 

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/possible-haven-397802/kube/bug:$SHORT_SHA'

# - name: "gcr.io/cloud-builders/gke-deploy"
#   id: GKE Deploy
#   args:
#   - run
#   - --filename=k8s/all.yaml
#   - --image=us-central1-docker.pkg.dev/possible-haven-397802/kube/test:$SHORT_SHA
#   - --location=us-central1
#   - --cluster=gke-cicd-prod
