name: Deploy  BUG to GKE

on:
  push:
    branches:
      - 'dev'

jobs:

  build:
    runs-on: ubuntu-latest
    name: Run all Scan Types
    steps:
      - uses: actions/checkout@master

      - name: RunSnyk to Opensource Test for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: test 
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: RunSnyk SAST Test
        uses: snyk/actions/node@master
        with:
          command: code test 
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - uses: actions/checkout@master
      - name: Run Snyk Monitor
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor   
      
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
    - name: code checkout
      uses: actions/checkout@v2
      
    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/possible-haven-397802/bugs/bugzy-dev:v1 .
        docker push us-central1-docker.pkg.dev/possible-haven-397802/bugs/bugzy-dev:v1